# 项目相关配置
project:

  # 文件路径 示例（ Windows配置D:/bosch/uploadPath，Linux配置 /home/RBLC/uploadPath）
#  profile: /mnt/resource/data/uploadPath
  profile: C:/Users/guz1cgd4/Pictures/Screenpresso
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: @profiles.active@
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.bosch: info
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
      location: /data/upload_tmp
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: @redis.host@
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: @redis.password@
    # 连接超时时间
    timeout: 5000
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
    jedis:
     pool:
       # 连接池中的最小空闲连接
       min-idle: 0
       # 连接池中的最大空闲连接
       max-idle: 5
       # 连接池最大连接数（使用负值表示没有限制,不要配置过大，否则可能会影响redis的性能）
       max-active: 40
       # 连接池最大阻塞等待时间（使用负值表示没有限制）；单位毫秒
       max-wait: 5000
       #设置驱逐空闲连接的时间间隔
       time-between-eviction-runs: 30000

  mail:
    host: smtp.qq.com
    port: 587
    username: 2424834965@qq.com
    password: isoprmksyfrqdiai
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true




# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.bosch.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml,classpath*:mapper/*Mapper.xml
  type-aliases-package: com.bosch.**.domain
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

depts: 测试部门,工厂部门

rocketmq:
  name-server: localhost:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group
    topic: my-topic
